import Foundation

/// Presentation-only localization. Internal state values and user content stay unchanged.
enum DisplayLanguage: String, Codable, CaseIterable, Identifiable, Sendable {
    case chinese = "zh-CN", english = "en"
    var id: String { rawValue }
    var title: String { self == .chinese ? "简体中文" : "English" }
    var locale: Locale { Locale(identifier: self == .chinese ? "zh_CN" : "en_US") }
    func menuErrorSummary(_ source: String) -> String {
        switch source {
        case "蓝牙权限未允许。请在系统设置中允许伴侣应用后重试。",
             "蓝牙权限未允许。请在系统设置中允许此伴侣应用。":
            return self == .english ? "Bluetooth access denied" : "蓝牙权限未开启"
        default:
            let firstLine = text(source).split(whereSeparator: \.isNewline).first.map(String.init) ?? ""
            let summary = firstLine.components(separatedBy: "。")[0]
                .components(separatedBy: ". ")[0].trimmingCharacters(in: .whitespaces)
            let limit = self == .english ? 36 : 18
            return summary.count > limit ? String(summary.prefix(limit)) + "…" : summary
        }
    }
    func text(_ source: String) -> String {
        guard self == .english else { return source }
        if let translated = Self.englishStrings[source] { return translated }
        // Only known application message envelopes are decomposed. Never substitute
        // arbitrary substrings in device names, task names, paths or external errors.
        for (prefix, translated) in Self.prefixes where source.hasPrefix(prefix) {
            return translated + text(String(source.dropFirst(prefix.count)))
        }
        if source.contains("\n") { return source.components(separatedBy: "\n").map(text).joined(separator: "\n") }
        if source.hasPrefix("正在下发 "), source.hasSuffix("/129 包") {
            return "Sending packet " + source.dropFirst(5).dropLast(2)
        }
        if source.hasPrefix("同步未完成（"), source.hasSuffix("）；保留未确认请求，可重试。") {
            let code = source.dropFirst(6).dropLast("）；保留未确认请求，可重试。".count)
            return "Sync incomplete (\(code)). The pending request can be retried."
        }
        return source
    }
    private static let prefixes: [(String, String)] = [
        ("配置检查失败：", "Setup check failed: "),
        ("发送前配置校验未通过：", "Pre-send setup check failed: "),
        ("无法确认安装状态。", "Cannot confirm setup status. "),
        ("操作未完成：", "Operation incomplete: "),
        ("登录启动未更改：", "Login startup was not changed: ")
    ]
    private static let englishStrings: [String: String] = [
        "Codex Ink · 设置": "Codex Ink · Settings",
        "仍未确认蓝牙连接清理": "Bluetooth disconnection is not yet confirmed",
        "退出会结束本应用的蓝牙所有权。未完成发送不会确认为成功；下次启动需重试。": "Quitting releases Bluetooth ownership. Incomplete transfers remain unconfirmed and need a retry on the next launch.",
        "退出": "Quit",
        "继续同步": "Resume sync",
        "暂停同步": "Pause sync",
        "正在暂停…": "Pausing…",
        "查看预览": "Preview",
        "设置…": "Settings…",
        "查看详情…": "View details…",
        "暂无记录": "No records yet",
        "退出 Codex Ink": "Quit Codex Ink",
        "尚无成功记录": "No successful record",
        "停止伴侣同步并恢复本应用旧配置？": "Stop sync and restore the previous configuration?",
        "备份并接管本应用的 hooks 与旧启动项？": "Back up and take over this app’s hooks and login item?",
        "停止并恢复": "Stop and restore",
        "确认接管": "Confirm takeover",
        "取消": "Cancel",
        "不会自动退出 Codex、绕过 hooks 信任或覆盖其他应用的 hooks。条件不满足时停止并保留原配置。": "Codex must be closed manually. Hook trust is required and other apps’ hooks are preserved. If checks fail, the original configuration is kept.",
        "概览": "Overview",
        "查看屏幕内容与同步状态": "View the display and sync status",
        "真实数据生成的 400×300 墨水屏预览，非已下发确认": "400×300 preview from real data; delivery is not confirmed",
        "尚无有效预览": "No valid preview",
        "先到“数据源”检查真实数据": "Check real data in Data source first",
        "预览不代表设备已更新；下发成功也不替代实屏确认。": "A preview does not confirm delivery. Check the physical display after sending.",
        "墨水屏预览": "Display preview",
        "运行状态": "Status",
        "绑定设备": "Bound display",
        "最近读取": "Last read",
        "最近下发": "Last sent",
        "当前状态": "Current status",
        "数据源": "Data source",
        "连接 Codex 并验证真实数据": "Connect to Codex and validate real data",
        "Codex 可执行文件": "Codex executable",
        "Python 可执行文件": "Python executable",
        "保存路径": "Save paths",
        "检查数据并生成预览": "Check data and preview",
        "只读取 Codex 现有登录状态，不保存密码，不调用模型。首次配置只生成预览，不发送画面。": "Uses the existing Codex login without storing passwords or calling a model. First-time setup only generates a preview.",
        "本地运行环境": "Local runtime",
        "墨水屏": "Display",
        "扫描并绑定唯一的发送目标": "Find and bind the display to receive updates",
        "当前设备": "Current display",
        "本机标识": "Local identifier",
        "扫描设备": "Scan for displays",
        "停止蓝牙操作": "Stop Bluetooth operation",
        "验证并绑定": "Validate and bind",
        "名称只供辨认。连接后会验证服务、写入特征及包长，确认断开后才保存本机 UUID。扫描或重绑会关闭自动同步。": "Names identify devices only. The service, write characteristic and packet size are checked before saving the UUID after disconnection. Scanning or rebinding disables automatic sync.",
        "设备绑定": "Display binding",
        "自动同步": "Automatic sync",
        "管理 Hooks、发送状态和登录启动": "Manage hooks, sync and login startup",
        "安装检查": "Setup check",
        "旧方案检查尚未完成": "Previous setup check is incomplete",
        "检查接管状态": "Check setup",
        "安装 / 接管…": "Install / take over…",
        "接管会备份并替换本应用已识别的 Hooks，保留其他 Hooks。请自行退出旧 Codex 会话；应用不会替你关闭 Codex。": "Takeover backs up and replaces this app’s recognized hooks, preserving other hooks. Quit existing Codex sessions yourself before continuing.",
        "接管后重新打开 Codex，审阅并信任新 Hooks。只有真实检查为 ready 才能启用同步。": "Reopen Codex and review and trust the new hooks. Sync can be enabled only after setup checks report ready.",
        "Hooks 与接管": "Hooks and takeover",
        "启用同步": "Enable sync",
        "立即刷新": "Refresh now",
        "登录时打开": "Open at login",
        "系统登录项": "Login item",
        "打开系统登录项设置": "Open Login Items settings",
        "系统中关闭后不会自动重新注册。登录恢复会沿用当前有效配置目录。": "Disabling the login item in system settings is respected. Login startup uses the current valid configuration directory.",
        "同步与启动": "Sync and startup",
        "恢复旧配置…": "Restore previous setup…",
        "仅在需要退出当前接管方案时使用。恢复仍会检查冲突并保留其他 Hooks。": "Use this to leave the current setup. Restoration checks for conflicts and preserves other hooks.",
        "维护与恢复": "Maintenance and recovery",
        "正在执行本地操作": "Running a local operation",
        "重新检查": "Check again",
        "查看状态目录": "Open state folder",
        "选择…": "Choose…",
        "已验证，可启用": "Verified, ready to enable",
        "尚未安装": "Not installed",
        "旧方案仍在运行": "Previous setup is still active",
        "等待 Codex 信任与新事件": "Waiting for Codex trust and a new event",
        "需要处理": "Needs attention",
        "尚未确认": "Not confirmed",
        "就绪": "Ready",
        "同步中": "Syncing",
        "等待恢复": "Waiting to recover",
        "已暂停": "Paused",
        "尚无记录": "No record",
        "开发版": "Development",
        "已启用": "Enabled",
        "等待系统允许": "Awaiting system approval",
        "未启用": "Disabled",
        "当前应用无法注册": "This app cannot register",
        "尚未读取真实数据": "Real data has not been read yet",
        "正在退出": "Quitting",
        "正在暂停": "Pausing",
        "待配置": "Setup required",
        "完成配置": "Complete setup",
        "重试": "Retry",
        "尚未绑定屏幕": "No display bound",
        "请选择可执行的 Codex 和 Python 文件；数据/依赖检查由预览完成。": "Choose executable Codex and Python files. Preview checks the data and dependencies.",
        "真实数据检查未通过。请确认 Codex 登录、每周额度和用量历史可读取；旧预览保留。": "Data validation failed. Check Codex login, weekly quota and usage history. Any existing preview is retained.",
        "账号、每周额度和用量历史检查通过": "Account, weekly quota and usage history validated",
        "数据尚未就绪；未发送": "Data is not ready; nothing sent",
        "已请求恢复旧配置；请检查 Codex 信任与旧启动状态。伴侣同步保持关闭。": "Restoration requested. Check Codex trust and the previous startup configuration. Companion sync remains disabled.",
        "请重新打开 Codex，审阅并信任新 hooks；收到新事件后再检查配置。": "Reopen Codex, review and trust the new hooks, then check setup after a new event arrives.",
        "请先验证并绑定设备，完成 setup 检查；未信任的新 hooks 不能解锁同步。": "Validate and bind a display and complete setup checks first. New hooks must be trusted before sync can start.",
        "请先点击“检查数据并生成预览”。": "Click “Check data and preview” first.",
        "尚未启用同步或配置未就绪；立即刷新不会越过配置门禁。": "Sync is disabled or setup is incomplete. Refresh cannot bypass setup checks.",
        "旧蓝牙连接尚未清理；不能开始新的会话。": "The previous Bluetooth connection is not cleared. A new session cannot start.",
        "请先保存配置，再开启登录启动。": "Save the configuration before enabling login startup.",
        "数据进程未在期限内就绪。": "The data process did not become ready in time.",
        "最近一次真实数据读取成功": "The latest real-data read succeeded",
        "帧校验失败：不是校验和匹配的原生 400×300 三色 PNG。": "Frame validation failed: expected a native 400×300 three-color PNG with a matching checksum.",
        "数据进程已退出；等待蓝牙清理后重试。": "The data process exited. Retry after Bluetooth cleanup.",
        "旧进程或蓝牙连接尚未清理；已阻止后续操作。": "The previous process or Bluetooth connection is still active. Further operations are blocked.",
        "无法加载真实预览。": "Cannot load the real-data preview.",
        "同步账本不可读取；未确认下发状态。": "Cannot read the sync journal. Delivery status is unconfirmed.",
        "蓝牙权限未允许。请在系统设置中允许伴侣应用后重试。": "Bluetooth access is denied. Allow this app in System Settings, then retry.",
        "蓝牙已关闭。开启蓝牙后重试。": "Bluetooth is off. Turn it on and retry.",
        "真实数据暂不可用；保留设备旧画面。请检查 Codex 登录和数据读取。": "Real data is unavailable. The display keeps its previous frame. Check Codex login and data access.",
        "未满足设备绑定或安全接管条件；没有发送。": "Display binding or takeover checks are incomplete. Nothing sent.",
        "帧校验未通过；没有发送。": "Frame validation failed. Nothing sent.",
        "发送或断开超时；未确认画面更新。": "Transfer or disconnection timed out. The display update is unconfirmed.",
        "数据管道读取失败。": "Failed to read the data pipe.",
        "旧数据进程尚未退出。": "The previous data process has not exited.",
        "Python 可执行文件不可用。": "The Python executable is unavailable.",
        "无法建立非阻塞控制管道。": "Cannot create a nonblocking control pipe.",
        "无法启动数据进程；请检查 Python 和运行目录。": "Cannot start the data process. Check Python and the runtime directory.",
        "数据管道已关闭。": "The data pipe is closed.",
        "数据管道写入失败。": "Failed to write to the data pipe.",
        "另一个本地检查尚未结束。": "Another local check is still running.",
        "无法运行本地检查；请检查可执行路径和 runtime。": "Cannot run the local check. Check executable paths and the runtime.",
        "本地检查超时，未启用同步。": "The local check timed out. Sync was not enabled.",
        "本地检查已取消。": "The local check was cancelled.",
        "本地检查返回超过大小限制，结果已拒绝。": "The local check exceeded the output limit. Results were rejected.",
        "只读检查进程退出后输出管道未关闭；结果已拒绝。": "The read-only check exited but its output pipe stayed open. Results were rejected.",
        "设置无效：请检查可执行路径和设备绑定。": "Invalid settings. Check executable paths and display binding.",
        "settings.json 损坏或版本不支持；已停止同步，原文件未覆盖。请修复文件后重试。": "settings.json is damaged or unsupported. Sync is stopped and the file is preserved. Repair it before retrying.",
        "startup.json 无效或所选配置已丢失/损坏；已停止自动恢复。请修复启动记录及其指向的 settings.json 后重新打开，原文件未覆盖。": "startup.json or its selected configuration is invalid or missing. Automatic recovery stopped. Repair the startup record and its settings.json, then reopen. Original files are preserved.",
        "仅支持绝对路径参数 --state-dir 和 --runtime-root。": "Only absolute --state-dir and --runtime-root paths are supported.",
        "此用户已有伴侣应用持有控制权。": "Another companion app already owns control for this user.",
        "数据进程协议不匹配；会话已停止。": "Data process protocol mismatch. The session is stopped.",
        "数据进程消息超过 1 MiB，已停止会话。": "A data process message exceeded 1 MiB. The session is stopped.",
        "数据进程在完整消息前退出。": "The data process exited before completing a message.",
        "无法建立应用所有权锁。": "Cannot acquire the app ownership lock.",
        "检测到旧方案配置。": "Previous setup detected.",
        "未检测到已识别的旧方案配置。": "No recognized previous setup detected.",
        "请自行退出 Codex 会话后再接管；应用不会代为关闭。": "Quit Codex sessions before takeover. This app will not close them for you.",
        "旧发送者仍在运行，请等待本次发送结束。": "The previous sender is still running. Wait for it to finish.",
        "另一个伴侣进程仍在运行，请先退出它。": "Another companion process is running. Quit it first.",
        "旧启动项或旧 hooks 仍在活动，接管尚未完成。": "Previous login items or hooks are active. Takeover is incomplete.",
        "状态目录必须位于当前用户目录中，不能使用 /tmp、符号链接或不安全路径。": "The state directory must be inside your home folder. Temporary, symbolic-link and unsafe paths are not allowed.",
        "应用运行目录位于临时目录；正式接管前请移到稳定位置。": "The app runtime is in a temporary directory. Move it to a stable location before takeover.",
        "存在无法安全识别的 hooks 来源；请先核查，不会自动覆盖。": "Some hook sources cannot be identified safely. Review them first; they will not be overwritten.",
        "配置在检查后发生变化；请核对当前文件与备份，禁止整体覆盖。": "Configuration changed after inspection. Compare current files and backups; do not overwrite the whole configuration.",
        "配置文件不可解析；请先修复原文件。": "Cannot parse the configuration. Repair the original file first.",
        "另一个接管操作尚未结束，请稍后重新检查。": "Another takeover is in progress. Check again later.",
        "接管存在未完成步骤；请核对备份和状态后恢复。": "Takeover has unfinished steps. Check backups and status before restoring.",
        "运行脚本或安装路径与记录不符；请核对稳定运行目录。": "Runtime scripts or installation paths do not match the record. Check the runtime directory.",
        "安装记录或新 hook 事件凭据无效；请重新检查配置与信任流程。": "The installation record or new hook event evidence is invalid. Recheck setup and trust.",
        "无法确认旧进程已停止；为防止双发送，接管被阻止。": "Cannot confirm the old process stopped. Takeover is blocked to prevent two senders.",
        "无法安全确认或停用本应用旧启动项；请检查启动项状态。": "Cannot safely verify or disable this app’s previous login item. Check its status.",
        "无法安全读取或备份配置；请检查文件权限、大小与可用空间。": "Cannot safely read or back up configuration. Check file permissions, size and free space.",
        "条件未满足，请核对本地安装记录后重试。": "Requirements are not met. Check the local installation record and retry.",
        "未请求蓝牙授权": "Bluetooth permission not requested",
        "正在检查蓝牙授权…": "Checking Bluetooth permission…",
        "请重新扫描并选择设备。": "Scan again and select a display.",
        "正在连接已绑定屏幕…": "Connecting to the bound display…",
        "正在停止蓝牙操作…": "Stopping Bluetooth operation…",
        "正在验证屏幕服务…": "Validating display services…",
        "蓝牙权限未允许。请在系统设置中允许此伴侣应用。": "Bluetooth access is denied. Allow this app in System Settings.",
        "蓝牙已关闭。开启后可重试。": "Bluetooth is off. Turn it on to retry.",
        "此 Mac 不支持所需蓝牙功能。": "This Mac does not support the required Bluetooth features.",
        "正在扫描；请选择你的屏幕。": "Scanning. Select your display.",
        "正在寻找已绑定屏幕…": "Searching for the bound display…",
        "未命名设备": "Unnamed display",
        "设备没有匹配的 EPD 服务，未保存绑定。": "No matching EPD service. Binding was not saved.",
        "设备写入特征或包长不兼容，未保存绑定。": "Incompatible write characteristic or packet size. Binding was not saved.",
        "设备通知初始化失败。": "Failed to initialize device notifications.",
        "数据包写入失败；未确认此帧。": "Packet write failed. This frame is unconfirmed.",
        "129/129 包已写入并确认断开；实屏外观仍需确认。": "129/129 packets written and disconnection confirmed. Check the physical display.",
        "服务验证通过，已断开。": "Service validated and disconnected.",
        "设备提前断开；未确认发送。": "The device disconnected early. Delivery is unconfirmed.",
        "未发现设备。确认屏幕可发现后重新扫描。": "No display found. Make it discoverable and scan again.",
        "扫描已结束；请选择要绑定的屏幕。": "Scan complete. Select a display to bind.",
        "断开未获确认，已阻止重连。等待系统断开回调，或退出后重试。": "Disconnection is unconfirmed, so reconnection is blocked. Wait for confirmation or quit and retry.",
        "蓝牙操作超过本帧时间预算，正在清理连接。": "Bluetooth exceeded the frame deadline. Cleaning up the connection.",
        "发送条件已变化；当前帧保持待处理。": "Send conditions changed. The current frame remains pending.",
        "配置检查正在进行，当前帧已延后；没有使用缓存授权。": "Setup inspection is running. The frame is deferred until fresh authorization is available.",
        "检查期间发送条件已变化；没有发送。": "Send conditions changed during inspection. Nothing sent.",
        "安装或信任状态已变化，请重新检查配置。": "Installation or trust status changed. Check setup again.",
        "配置检查后已无发送时间预算；没有发送。": "No transfer time remains after setup inspection. Nothing sent.",
        "无法完成本帧配置检查；没有发送。": "Cannot complete setup inspection for this frame. Nothing sent."
    ]
}
